"""LangGraph workflow 同步运行器 — 内嵌 content-agent。"""

import asyncio
import importlib
import sys
import types
from pathlib import Path

from app.core.config import get_settings
from app.core.logging import get_logger

logger = get_logger("ai.workflow")
settings = get_settings()

_CA_ROOT = Path(__file__).resolve().parent / "content_agent"
_CONFIG_DIR = Path(__file__).resolve().parent / "config"


def _ensure_content_agent_app_package() -> None:
    """将 content_agent 目录挂载为顶层 app 包（兼容原侧车 import 路径）。"""
    if "app" in sys.modules and hasattr(sys.modules["app"], "__geoflow_ca__"):
        return
    app_pkg = types.ModuleType("app")
    app_pkg.__path__ = [str(_CA_ROOT)]  # type: ignore[attr-defined]
    app_pkg.__geoflow_ca__ = True  # type: ignore[attr-defined]
    sys.modules["app"] = app_pkg
    import os

    os.environ.setdefault("CONTENT_AGENT_CONFIG_DIR", str(_CONFIG_DIR))


def run_workflow_sync(workflow_type: str, payload: dict) -> dict:
    if settings.ai_mock_mode:
        return _mock_result(workflow_type, payload)

    try:
        _ensure_content_agent_app_package()
        graph_runner = importlib.import_module("app.orchestration.graph_runner")
        run_fn = graph_runner.run_configured_workflow
        try:
            loop = asyncio.get_event_loop()
            if loop.is_running():
                import concurrent.futures

                with concurrent.futures.ThreadPoolExecutor() as pool:
                    return pool.submit(asyncio.run, run_fn(workflow_type, payload)).result()
            return loop.run_until_complete(run_fn(workflow_type, payload))
        except RuntimeError:
            return asyncio.run(run_fn(workflow_type, payload))
    except Exception as exc:  # noqa: BLE001
        logger.warning("workflow_fallback_mock", workflow=workflow_type, error=str(exc))
        return _mock_result(workflow_type, payload)


def _mock_result(workflow_type: str, payload: dict) -> dict:
    prompt = payload.get("prompt", "")[:80]
    content = f"# Mock {workflow_type}\n\n{prompt}\n\n> Generated by GEOFlow v3 mock mode."
    return {
        "content": content,
        "title": f"Mock: {workflow_type}",
        "citations": payload.get("evidence", [])[:3],
        "engine": "mock",
    }
