"""LangGraph workflow 同步运行器 — 内嵌 content-agent。"""

import asyncio
import importlib
import re
import sys
import types
from pathlib import Path

from app.core.config import get_settings
from app.core.logging import get_logger

logger = get_logger("ai.workflow")
settings = get_settings()

_CA_ROOT = Path(__file__).resolve().parent / "content_agent"
_CONFIG_DIR = Path(__file__).resolve().parent / "config"


def _ensure_content_agent_app_package() -> None:
    """将 content_agent 目录挂载为顶层 app 包（兼容原侧车 import 路径）。"""
    if "app" in sys.modules and hasattr(sys.modules["app"], "__geoflow_ca__"):
        return
    app_pkg = types.ModuleType("app")
    app_pkg.__path__ = [str(_CA_ROOT)]  # type: ignore[attr-defined]
    app_pkg.__geoflow_ca__ = True  # type: ignore[attr-defined]
    sys.modules["app"] = app_pkg
    import os

    os.environ.setdefault("CONTENT_AGENT_CONFIG_DIR", str(_CONFIG_DIR))


def run_workflow_sync(workflow_type: str, payload: dict) -> dict:
    if settings.ai_mock_mode:
        return _mock_result(workflow_type, payload)

    try:
        _ensure_content_agent_app_package()
        graph_runner = importlib.import_module("app.orchestration.graph_runner")
        run_fn = graph_runner.run_configured_workflow
        try:
            loop = asyncio.get_event_loop()
            if loop.is_running():
                import concurrent.futures

                with concurrent.futures.ThreadPoolExecutor() as pool:
                    return pool.submit(asyncio.run, run_fn(workflow_type, payload)).result()
            return loop.run_until_complete(run_fn(workflow_type, payload))
        except RuntimeError:
            return asyncio.run(run_fn(workflow_type, payload))
    except Exception as exc:  # noqa: BLE001
        logger.warning("workflow_fallback_mock", workflow=workflow_type, error=str(exc))
        return _mock_result(workflow_type, payload)


def _extract_keywords(text: str, limit: int = 8) -> list[str]:
    parts = re.findall(r"[\u4e00-\u9fff]{2,}|[a-zA-Z]{4,}", text)
    seen: set[str] = set()
    out: list[str] = []
    for p in parts:
        if p.lower() not in seen:
            seen.add(p.lower())
            out.append(p)
        if len(out) >= limit:
            break
    return out


def _mock_result(workflow_type: str, payload: dict) -> dict:
    if workflow_type == "url_import":
        page = payload.get("page_json") if isinstance(payload.get("page_json"), dict) else {}
        text = str(page.get("text") or page.get("title") or payload.get("url", ""))[:6000]
        title = str(page.get("title") or "导入知识库")
        keywords = _extract_keywords(text)
        return {
            "summary": text[:280] or f"从 {payload.get('url', 'URL')} 导入",
            "library_name": title,
            "keywords": keywords,
            "titles": [f"{title} · 深度解读", f"{title} · 核心要点", f"{title} · 行业趋势"][: max(3, min(5, len(keywords) + 2))],
            "knowledge_markdown": f"# {title}\n\n{text[:4000]}\n\n> 来源：{payload.get('url', 'inline')}",
            "analysis_source": "mock",
            "engine": "mock",
        }

    if workflow_type == "semantic_chunk":
        content = str(payload.get("content") or "")[:2000]
        return {
            "chunks": [{"index": 0, "content": content[:800]}, {"index": 1, "content": content[800:1600]}],
            "engine": "mock",
        }

    prompt = payload.get("prompt", "")[:80]
    content = f"# Mock {workflow_type}\n\n{prompt}\n\n> Generated by GEOFlow v3 mock mode."
    return {
        "content": content,
        "title": f"Mock: {workflow_type}",
        "citations": payload.get("evidence", [])[:3] if isinstance(payload.get("evidence"), list) else [],
        "engine": "mock",
    }
