"""Mock / linear 引擎 — 对齐 GEOFlow workflow 输出契约。"""

from __future__ import annotations

import re
from typing import Any

from content_lg.config import get_workflow
from content_lg.utils.logger import get_logger

logger = get_logger("content_lg.engine")

TERMINAL_NODES = {"finalize", "build_chunks", "deputy_finalize"}


def extract_keywords(text: str, limit: int = 8) -> list[str]:
    parts = re.findall(r"[\u4e00-\u9fff]{2,}|[a-zA-Z]{4,}", text)
    seen: set[str] = set()
    out: list[str] = []
    for p in parts:
        key = p.lower()
        if key not in seen:
            seen.add(key)
            out.append(p)
        if len(out) >= limit:
            break
    return out


def mock_result(workflow_type: str, payload: dict[str, Any], *, trace: list[str] | None = None) -> dict[str, Any]:
    """对齐 GEOFlow workflow_runner._mock_result 输出形状。"""
    steps = list(trace or [])

    if workflow_type == "url_import":
        page = payload.get("page_json") if isinstance(payload.get("page_json"), dict) else {}
        text = str(page.get("text") or page.get("title") or payload.get("url", ""))[:6000]
        title = str(page.get("title") or "导入知识库")
        keywords = extract_keywords(text)
        result = {
            "summary": text[:280] or f"从 {payload.get('url', 'URL')} 导入",
            "library_name": title,
            "keywords": keywords,
            "titles": [
                f"{title} · 深度解读",
                f"{title} · 核心要点",
                f"{title} · 行业趋势",
            ][: max(3, min(5, len(keywords) + 2))],
            "knowledge_markdown": f"# {title}\n\n{text[:4000]}\n\n> 来源：{payload.get('url', 'inline')}",
            "analysis_source": "mock",
            "engine": "mock",
        }
        if steps:
            result["trace"] = {"steps": steps}
        return result

    if workflow_type == "semantic_chunk":
        content = str(payload.get("content") or "")[:2000]
        result = {
            "chunks": [
                {"index": 0, "content": content[:800]},
                {"index": 1, "content": content[800:1600]},
            ],
            "engine": "mock",
        }
        if steps:
            result["trace"] = {"steps": steps}
        return result

    prompt = str(payload.get("prompt", ""))[:80]
    title = str(payload.get("title") or payload.get("user_request") or f"Mock: {workflow_type}")
    content = f"# {title}\n\n{prompt}\n\n> Generated by content-lg mock mode."
    result = {
        "content": content,
        "title": title,
        "citations": payload.get("evidence", [])[:3] if isinstance(payload.get("evidence"), list) else [],
        "engine": "mock",
    }
    if steps:
        result["trace"] = {"steps": steps}
    return result


def _matches_when(when: str, state: dict[str, Any]) -> bool:
    if when == "needs_revision":
        return bool(state.get("needs_revision"))
    if when == "ok":
        return not state.get("needs_revision") and not state.get("skip_compliance")
    if when == "skip_compliance":
        return bool(state.get("skip_compliance")) and not state.get("needs_revision")
    if when == "fast_mode":
        return str(state.get("pipeline_path") or "") == "fast"
    if when == "deep_mode":
        return str(state.get("pipeline_path") or "") != "fast"
    compliance = state.get("compliance") if isinstance(state.get("compliance"), dict) else {}
    if when == "compliance_pass":
        return bool(compliance.get("passed", True))
    if when == "compliance_reject":
        return compliance.get("passed") is False
    return False


def _resolve_next(current: str, edges: list[dict[str, Any]], state: dict[str, Any]) -> str | None:
    candidates = [e for e in edges if str(e.get("from") or "") == current]
    if not candidates:
        return None
    conditional = [e for e in candidates if e.get("when")]
    if conditional:
        for edge in conditional:
            if _matches_when(str(edge.get("when") or ""), state):
                return str(edge.get("to") or "") or None
        return str(conditional[-1].get("to") or "") or None
    return str(candidates[0].get("to") or "") or None


def walk_trace(workflow_type: str, payload: dict[str, Any]) -> list[str]:
    """按 workflows.yml 线性走图，记录节点（mock 节点不调用 LLM）。"""
    workflow = get_workflow(workflow_type)
    nodes = {
        str(n["id"]): n
        for n in workflow.get("nodes", [])
        if isinstance(n, dict) and n.get("id")
    }
    edges = [e for e in workflow.get("edges", []) if isinstance(e, dict)]
    start = next((str(e.get("to")) for e in edges if e.get("from") == "__start__"), None)
    if not start:
        return []

    state: dict[str, Any] = {"payload": payload, "needs_revision": False}
    mode = str(payload.get("pipeline_mode") or "fast").lower()
    state["pipeline_path"] = "fast" if mode in {"fast", "legacy", "standard"} and mode != "deep" else mode
    if workflow_type == "content_pipeline":
        # demo 默认 fast，跳过合规环
        if mode == "deep":
            state["pipeline_path"] = "deep"
            state["skip_compliance"] = False
            state["compliance"] = {"passed": True}
        else:
            state["pipeline_path"] = "fast"
            state["skip_compliance"] = True
            state["compliance"] = {"passed": True}

    current = start
    steps: list[str] = []
    guard = 0
    while current and guard < 32:
        guard += 1
        if current not in nodes:
            break
        steps.append(current)
        if current in TERMINAL_NODES:
            break
        nxt = _resolve_next(current, edges, state)
        if not nxt or nxt == current:
            break
        current = nxt
    logger.debug("workflow_trace type=%s steps=%s", workflow_type, steps)
    return steps


def run_linear_mock(workflow_type: str, payload: dict[str, Any]) -> dict[str, Any]:
    steps = walk_trace(workflow_type, payload)
    return mock_result(workflow_type, payload, trace=steps)
